name: CI

on:
  push:
    branches:
      - master
      - versions/*
  pull_request:
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    name: Linter with SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@master
        with:
          args: --strict

  test:
    name: Test with fastlane
    runs-on: macOS-latest
    strategy:
      matrix:
        ruby: ['2.7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run test
        run: make test USE_RBENV=false

      - name: Send converage
        uses: codecov/codecov-action@v1
        with:
          file: fastlane/test_output/cobertura.xml
          fail_ci_if_error: false
